package com.monalisa.vacineja.enums;


public enum Comorbidity{

        ASMA,
        DISPLASIABRONCOPULMONAR,
        DIABETES,
        DOENCASRENAISCRONICAS,
        DOENCASHEMATOLOGICAS,
        DOENCASCARDIACAS,
        DOENCASRESPIRATORIASCRONICAS,
        DOENCASPULMONARES,
        FIBROSECISTICA,
        HEPATOPATIAS,
        IMUNOSSUPRESSOS,
        NEFROPATIAS,
        OBESIDADE,
        PACIENTESEMDIALISE,
        PORTADORESDEDOENCASCROMOSSOMICAS,
        TRANSPLANTADOSDEORGAOSSOLIDOSEDEMEDULAOSSEA
}
