import { Injectable } from '@angular/core';
import { UserData } from '../models/user-data';

@Injectable({ providedIn: 'root' })
export class UsuarioService {
  usuarios: UserData[] = [
    {
      nome: 'Maria',
      sobrenome: 'Teresa dos Santos',
      cpf: '48544219837',
      rua: 'Tamboré',
      cidade: 'Barueri',
      estado: 'SP',
      celular: '11977655918',
      telefone: '1141423098',
      email: 'maria_teresinha765@gmail.com',
      sexoBiologico: 'F',
      teveReacao: 'N',
      teveSintomas: 'N',
      temComorbidade: 'N',
      sintomasCovid: 'N',
      positivoCovid: 'N',
      fabricante: 'AstraZeneca',
      lote: '78906543',
      unidade: 'UBS Mario Andrade',
      vacinador: 'Valeria dos Santos Costa',
      regProf: '15996',
      lote2: '',
      vacinador2: '',
      regProf2: '',
      comorbidades: [],
      vacinas: [],
      dataVacinacao: new Date('08-07-2021'),
      dataVacinacao2: new Date('11-7-2021'),
      dataNascimento: new Date('12-31-1994'),
    },
    {
      nome: 'Joana',
      sobrenome: 'Jesus Martins de Lisboa',
      cpf: '11328219837',
      rua: 'R. dos Campineiros',
      cidade: 'São Paulo',
      estado: 'SP',
      celular: '11978655918',
      telefone: '1140023098',
      email: 'Joana4390@outlook.com.br',
      sexoBiologico: 'F',
      teveReacao: 'N',
      teveSintomas: 'S',
      temComorbidade: 'N',
      sintomasCovid: 'N',
      positivoCovid: 'N',
      fabricante: 'Pfizer',
      lote: '28906843',
      unidade: 'UBS Mooca I',
      vacinador: 'Edilson dos Santos Costa',
      regProf: '72996',
      lote2: '',
      vacinador2: '',
      regProf2: '',
      comorbidades: [],
      vacinas: [],
      dataVacinacao: new Date('04-25-2021'),
      dataVacinacao2: new Date('07-23-2021'),
      dataNascimento: new Date('03-07-1982'),
    },
    {
      nome: 'Otavio',
      sobrenome: 'Martins Marchioli',
      cpf: '54628219837',
      rua: 'R. Castanheiras',
      cidade: 'Barueri',
      estado: 'SP',
      celular: '11970955918',
      telefone: '1134023098',
      email: 'otavio.marchioli@outlook.com.br',
      sexoBiologico: 'M',
      teveReacao: 'N',
      teveSintomas: 'N',
      temComorbidade: 'N',
      sintomasCovid: 'N',
      positivoCovid: 'S',
      fabricante: 'CoronaVac',
      lote: '56906843',
      unidade: 'UBS Santa Tereza',
      vacinador: 'Antonio Matshjun Santos',
      regProf: '34996',
      lote2: '',
      vacinador2: '',
      regProf2: '',
      comorbidades: [],
      vacinas: [],
      dataVacinacao: new Date('8-13-2021'),
      dataVacinacao2: new Date('9-11-2021'),
      dataNascimento: new Date('04-07-1999'),
    },
    {
      nome: 'Flavia',
      sobrenome: 'Siva E Santos',
      cpf: '35648073810',
      rua: 'R. Castanheiras',
      cidade: 'Barueri',
      estado: 'SP',
      celular: '11970955918',
      telefone: '1134023098',
      email: 'otavio.marchioli@outlook.com.br',
      sexoBiologico: 'M',
      teveReacao: 'N',
      teveSintomas: 'N',
      temComorbidade: 'N',
      sintomasCovid: 'N',
      positivoCovid: 'S',
      fabricante: 'CoronaVac',
      lote: '56906843',
      unidade: 'EMEF Jose Correia',
      vacinador: 'Antonio Matshjun Santos',
      regProf: '34996',
      lote2: '',
      vacinador2: '',
      regProf2: '',
      comorbidades: [],
      vacinas: [],
      dataVacinacao: new Date('03-19-2021'),
      dataVacinacao2: new Date('04-22-2021'),
      dataNascimento: new Date('7-02-1976'),
    },
    {
      nome: 'Ana Clara',
      sobrenome: 'Coqueiro',
      cpf: '46753629080',
      rua: 'R. Castanheiras',
      cidade: 'Barueri',
      estado: 'SP',
      celular: '11970955918',
      telefone: '1134023098',
      email: 'otavio.marchioli@outlook.com.br',
      sexoBiologico: 'M',
      teveReacao: 'N',
      teveSintomas: 'N',
      temComorbidade: 'N',
      sintomasCovid: 'N',
      positivoCovid: 'S',
      fabricante: 'Janssen',
      lote: '56906843',
      unidade: 'UBS Antonio Marcos ',
      vacinador: 'Antonio Matshjun Santos',
      regProf: '34996',
      lote2: '',
      vacinador2: '',
      regProf2: '',
      comorbidades: [],
      vacinas: [],
      dataVacinacao: new Date('8-31-2021'),
      dataVacinacao2: new Date('0-00-0000'),
      dataNascimento: new Date('1-28-2000'),
    },
    {
      nome: 'Juliana',
      sobrenome: 'Silva',
      cpf: '77544219837',
      rua: 'Tamboré',
      cidade: 'Barueri',
      estado: 'SP',
      celular: '11977655918',
      telefone: '1141423098',
      email: 'maria_teresinha765@gmail.com',
      sexoBiologico: 'F',
      teveReacao: 'N',
      teveSintomas: 'N',
      temComorbidade: 'N',
      sintomasCovid: 'N',
      positivoCovid: 'N',
      fabricante: 'Pfizer',
      lote: '78906543',
      unidade: 'UBS Mario Andrade',
      vacinador: 'Valeria dos Santos Costa',
      regProf: '15996',
      lote2: '',
      vacinador2: '',
      regProf2: '',
      comorbidades: [],
      vacinas: [],
      dataVacinacao: new Date('6-23-2021'),
      dataVacinacao2: new Date('9-19-2021'),
      dataNascimento: new Date('1-28-1988'),
    },
    {
      nome: 'Daniel',
      sobrenome: 'Oliveira',
      cpf: '34328219837',
      rua: 'R. dos Campineiros',
      cidade: 'São Paulo',
      estado: 'SP',
      celular: '11978655918',
      telefone: '1140023098',
      email: 'Joana4390@outlook.com.br',
      sexoBiologico: 'F',
      teveReacao: 'N',
      teveSintomas: 'S',
      temComorbidade: 'N',
      sintomasCovid: 'N',
      positivoCovid: 'N',
      fabricante: 'Covaxin',
      lote: '67906843',
      unidade: 'UBS Mooca I',
      vacinador: 'Edilson dos Santos Costa',
      regProf: '72996',
      lote2: '',
      vacinador2: '',
      regProf2: '',
      comorbidades: [],
      vacinas: [],
      dataVacinacao: new Date('7-12-2021'),
      dataVacinacao2: new Date('8-10-2021'),
      dataNascimento: new Date('10-23-1990'),
    },
  ];

  deletar(i: number) {
    this.usuarios.splice(i, 1);
  }

  salvar(usuario: UserData) {
    this.usuarios.push({ ...usuario });
  }

  consultar(i: number) {
    return { ...this.usuarios[i] };
  }

  atualizar(usuario: UserData, i: number) {
    this.usuarios.splice(i, 1, usuario);
  }
}
